[package]
name = "bevy_baseview_plugin"
version = "0.1.0"
edition = "2021"
description = "A baseview window and input backend for Bevy Engine"
# homepage = "todo"
# repository = "https://github.com/todo"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "baseview", "gui"]

[features]
default = []
# Enables opengl contexts in baseview. Offered purely for compatibility, as bevy
# relies heavily on wgpu by default.
baseviewgl = []


[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", version = "*" }
crossbeam = { version = "0.8.*" }
crossbeam-channel = { version = "0.5.*" }
lazy_static = "1.5.0"
raw-window-handle = "0.4.3"
bevy = { version = "0.15.*" }
log = "0.4.22"
keyboard-types = { version = "0.6.2", default-features = false }
winit = "0.30.7"
